[variables]
NEXT_TELEMETRY_DISABLED = "1"

[phases.setup]
nixPkgs = ["python3"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["rm -rf .next/cache/* 2>/dev/null || true", "npm run build"]

[start]
cmd = "npx next start -p ${PORT:-8080}"
